# Generated by Django 4.1.4 on 2023-05-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('publisher_name', models.CharField(max_length=256)),
                ('publisher_age', models.CharField(choices=[('1', '20'), ('2', '25'), ('3', '30'), ('4', '40')], default=0, max_length=20)),
                ('page_no', models.IntegerField(default=0)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
