# Generated by Django 4.1.4 on 2023-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('1', 'Science'), ('2', 'Tech'), ('3', 'Lifestyle')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
