# Generated by Django 4.1.4 on 2023-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_genre_alter_book_publisher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('science', 'Science'), ('tech', 'Tech'), ('lifestyle', 'Lifestyle')], max_length=100),
        ),
    ]
