# Generated by Django 4.1.4 on 2023-05-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_age',
            field=models.CharField(choices=[('20', '20'), ('25', '25'), ('30', '30'), ('40', '40')], default=0, max_length=20),
        ),
    ]
